### ISSUE TITLE
Please push the two submodules

### ISSUE THREAD

**Issue by PhillipAnd** [gabek/TheBatPlayerRoku#2]
kthxbye ;-D

**Comment by gabek** [comment]
Pushed.  Let me know if it's happy now.
Also let me know if you want what your plans for the code is, if you're looking to contribute or use it as a jumping off point.  If you want to contribute I can hook you up with the values for the config file.

**Comment by PhillipAnd** [comment]
There is one of my favorite stations that crashes the player right after it downloads the info (http://provisioning.streamtheworld.com/pls/keloamaac.pls), and I figured I would go ahead and investigate and fix that.

If I copy the config-example, will it work even without valid Last-FM and Amplitude keys?

Also, what branches/tags represent the latest release pushed out to the Channel Store?

**Comment by gabek** [comment]
So that .pls file is actually a playlist file, not a stream, and currently The Bat Player doesn't know how to take a playlist and convert it internally into a playable stream.  (In the web interface it will when adding a station, however).

The actual audio stream seems to be http://3083.live.streamtheworld.com:80/KELOAMAAC_SC.  So you can try that.

**But** I just pushed a branch *roku-directory* that adds a new function called *GetDirectoryStation*.  This takes a station object with a *playlist* property, and tries to get the audio stream.  This branch adds some basic directory features to help station discovery.

With this new *GetDirectoryStation* function really the client should be updated to take either an audio stream **or** a playlist going forward, instead of just a stream like it is now.  You're free to look at that, if you want!

As far as the config file, I can send you my config file with all the values if you'd like to work on the project! Otherwise fill out the config with your own values and it should work.

**Comment by PhillipAnd** [comment]
It would be nice to have your config file...  sorry about the confusion, I did add the station using the Web interface... it plays fine for about five or ten seconds, and then immediately crashes when the info screen pops up, hmm...  
I won't have access to a Roku device until this weekend; in the meantime, I'll study the code so I debug it quickly when the time comes.

**Comment by gabek** [comment]
No problem.  What's an email I can send it to?

**Comment by PhillipAnd** [comment]
phillipedison1891 at g(-whiz-hope-this-can-fool-spambots-)mail dot com
