### ISSUE TITLE
BatUtils not defined in example Config and not documented so can't run the app

### ISSUE THREAD

**Issue by sidney** [gabek/TheBatPlayerRoku#7]
I'm trying to sideload the downloaded files from GitHub and I'm stuck at the config property BatUtils. I don't see any documentation about what to set it to. Main.brs line 38 gets an error if it isn't set in Config, but I can't find the URL where you are serving the json for defaultStations. The other settings in Config aren't fully documented either so I don't know if I will need valid values for AmplitudeApiKey or ImgixHost or SyslogServer, or how to get them if they do need valid values for the app to run.

**Comment by gabek** [comment]
Hi sidney,

Sorry to say these values are internally used by the production version of The Bat Player, so I can't share my personal credentials with you.

If you want to run the application exactly as it's used in production then feel free to sign up for your own accounts at Amplitude, Imgix, and any Syslog provider.  However I'd suggest you just pull those pieces of functionality from the application since it's for your own use and none of that is necessary for core functionality.

**Comment by sidney** [comment]
I get that the keys you use are your own and I would have to supply some or disable the functionality, but the big issue that I can't figure out by myself from looking at the code is what BatUtils is supposed to be set to and where you get the default stations and other configurations that you get from BatUtils. Do you have a publicly accessible server that BatUtils links to in the production channel? The issue here is to add this information to the README.md so that someone is able to clone the project and play with it locally.

**Comment by gabek** [comment]
That's fine, feel free to use https://batutils.thebatplayer.fm as an instance of Bat Utils.  It's for powering the directory.
